import React from 'react';
import './style.css';
import LikeIcon from '../../assets/Like';
import CommentIcon from '../../assets/Comment';
import ShareIcon from '../../assets/Share';
import RepostIcon from '../../assets/Repost';

const FeedCard = () => {
  return (
    <div className='card-container'>
      <div className='wrapper'>
        <div className='user-info'>
          <img
            className='avatar'
            src='https://avatars.githubusercontent.com/u/71932768?s=400&u=884a0a16cda8fb2fd86a966fa24aeba19107b7e9&v=4'
            alt='user profile pic'
          />
          <div className='user-text'>
            <p className='user-title'>
              Sunil <span className='time-ago'>1h</span>
            </p>
            <p className='user-headline'>What am I doing here???</p>
          </div>
        </div>

        <div>
          <p>
            Content creators are rewarded with LITIT for views generated by
            their videos. The LITIT Token is a new generation electronic
            currency of the Solana blockcha
          </p>
        </div>

        <div>
          <img
            className='post-image'
            src='https://torum-bucket.s3.us-east-2.amazonaws.com/5f0c4fd61039e53f6a231082/post/media/4dea2bacbe4b62820c6a5de9f3a05c9a_post_1679284976383.gif'
            alt='cat in car'
          />
        </div>

        <div className='social-bar'>
          <div className='social-options'>
            <LikeIcon />
            <CommentIcon />
            <ShareIcon />
            <RepostIcon />
          </div>
          <div></div>
        </div>

        <div className='comment-box'>
          <img
            className='avatar'
            src='https://avatars.githubusercontent.com/u/71932768?s=400&u=884a0a16cda8fb2fd86a966fa24aeba19107b7e9&v=4'
            alt='user profile pic'
          />
          <input type='text' placeholder='Comment on this...' />
        </div>
      </div>
    </div>
  );
};

export default FeedCard;
